# Generated by Django 5.1.15 on 2026-08-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_reservation_expires_at_payment_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('qr_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/%Y/%m/')),
                ('email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_attempts', models.PositiveIntegerField(default=0)),
                ('last_email_error', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='bookings.booking')),
            ],
        ),
    ]
