# Generated by Django 5.1.15 on 2026-08-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_ticket'),
        ('movies', '0006_movieimage_image_status_and_more'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['movie'], name='bookings_sh_movie_i_c143df_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['theater'], name='bookings_sh_theater_32c024_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['screen'], name='bookings_sh_screen__3cce6b_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['show_date'], name='bookings_sh_show_da_c05b50_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['start_time'], name='bookings_sh_start_t_375001_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['movie', 'show_date'], name='bookings_sh_movie_i_7020a2_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['theater', 'show_date'], name='bookings_sh_theater_ffceca_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['status', 'show_date'], name='bookings_sh_status_591d81_idx'),
        ),
    ]
