# Generated by Django 6.1 on 2026-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_backdrop_url',
            field=models.URLField(blank=True, help_text='Official TMDB Backdrop URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='The Movie Database ID', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_poster_url',
            field=models.URLField(blank=True, help_text='Official TMDB Poster URL', max_length=500, null=True),
        ),
    ]
