# Generated by Django 6.1 on 2026-08-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_backdrop_url_movie_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, help_text='TMDB backdrop_path e.g. /nMK28192i7WStCz2w34hZ1x8P7d.jpg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, help_text='TMDB poster_path e.g. /qJ2tW6WMUDux911r6m7haRef0WH.jpg', max_length=255, null=True),
        ),
    ]
