# Generated by Django 6.1 on 2026-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_backdrop_path_movie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('NOW_SHOWING', 'Now Showing'), ('RELEASED', 'Released'), ('ENDED', 'Ended'), ('ARCHIVED', 'Archived')], default='NOW_SHOWING', max_length=20),
        ),
    ]
