# Generated by Django 5.1.15 on 2026-08-16 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_country_alter_movie_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date'], name='movies_movi_release_e8f22e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-average_rating'], name='movies_movi_average_ace365_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_movi_title_652549_idx'),
        ),
        migrations.AddField(
            model_name='recentlyviewedmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_by', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recentlyviewedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recentlyviewedmovie',
            index=models.Index(fields=['user', '-viewed_at'], name='movies_rece_user_id_11ee21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewedmovie',
            unique_together={('user', 'movie')},
        ),
    ]
