# Generated by Django 5.1.15 on 2026-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_recentlyviewedmovie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieimage',
            name='image_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('MISSING', 'Missing'), ('BROKEN', 'Broken'), ('DUPLICATE', 'Duplicate Image'), ('SUSPECTED_WRONG_IMAGE', 'Suspected Wrong Image')], default='VALID', max_length=30),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='license_information',
            field=models.CharField(blank=True, default='Promotional / Fair Use', max_length=200),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='source_name',
            field=models.CharField(blank=True, default='Promotional Archive', max_length=100),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING_REVIEW', 'Pending Review'), ('COPYRIGHT_REVIEW', 'Copyright Review Required'), ('AMBIGUOUS', 'Ambiguous Match'), ('FAILED', 'Failed'), ('PLACEHOLDER', 'Placeholder')], default='VERIFIED', max_length=30),
        ),
    ]
