# Generated by Django 6.1 on 2026-08-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movieimage_image_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_source',
            field=models.CharField(blank=True, default='YouTube', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_type',
            field=models.CharField(blank=True, default='OFFICIAL_TRAILER', max_length=40),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MovieTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_url', models.URLField(max_length=500)),
                ('video_id', models.CharField(max_length=50)),
                ('video_title', models.CharField(max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=150)),
                ('channel_id', models.CharField(blank=True, max_length=100)),
                ('trailer_source', models.CharField(default='YouTube', max_length=50)),
                ('trailer_type', models.CharField(choices=[('OFFICIAL_TRAILER', 'Official Trailer'), ('OFFICIAL_TEASER', 'Official Teaser'), ('FINAL_TRAILER', 'Final Trailer'), ('INTERNATIONAL_TRAILER', 'International Trailer'), ('TV_SPOT', 'TV Spot'), ('CLIP', 'Official Clip'), ('BEHIND_THE_SCENES', 'Behind The Scenes'), ('INTERVIEW', 'Interview'), ('FEATURETTE', 'Featurette')], default='OFFICIAL_TRAILER', max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING_REVIEW', 'Pending Review'), ('MANUAL_REVIEW_REQUIRED', 'Manual Review Required'), ('NO_TRAILER_FOUND', 'No Trailer Found'), ('MULTIPLE_MATCHES', 'Multiple Matches'), ('TRAILER_UNAVAILABLE', 'Trailer Unavailable'), ('TRAILER_BROKEN', 'Trailer Broken'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=40)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes_or_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='movies.movie')),
            ],
            options={
                'ordering': ['-is_primary', '-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['movie', 'is_primary'], name='movies_movi_movie_i_b45ee0_idx'), models.Index(fields=['verification_status'], name='movies_movi_verific_0d0efb_idx'), models.Index(fields=['video_id'], name='movies_movi_video_i_db27b5_idx')],
            },
        ),
    ]
