# Generated by Django 6.1 on 2026-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_trailer_source_movie_trailer_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_source',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
    ]
