# Generated by Django 6.1 on 2026-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_poster_last_checked_movie_poster_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_source',
            field=models.CharField(blank=True, default='TMDB', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='media_status',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('manual_review', 'Manual Review'), ('missing_poster', 'Missing Poster'), ('missing_trailer', 'Missing Trailer')], default='ok', max_length=40),
        ),
    ]
